language: go
go:
  - 1.9

notificaitons:
  email:
    recipients: phillipsopaolacoding@gmail.com
    on_success: change
    on_failure: always

script:
  - go test -v .
install:
  - go get github.com/philangist/vimeo-indexer
