language: go
go:
  - 1.9

notificaitons:
  email:
    recipients: phillipsopaolacoding@gmail.com
    on_success: change
    on_failure: always

install:
  - go get github.com/philangist/vimeo-indexer

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
